#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Create SFT-CoT subsets from JSONL files generated by data_makes.py.

This script keeps the same schema and simply samples train split subsets for:
1) CoT-SFT retraining
2) Doctor preference learning bootstrapping
"""

from __future__ import annotations

import json
import random
from pathlib import Path
from typing import Dict, List

ROOT_DIR = Path("/media/ren9/Elements/exvla_clinical")
SEED = 42
SFT_TRAIN_RATIO = 0.10  # 10% train subset for fast CoT-SFT iteration

SOURCES = {
    "images": ROOT_DIR / "gastrohun_llm_en_images_train.jsonl",
    "seqs": ROOT_DIR / "gastrohun_llm_en_seqs_train.jsonl",
    "multimodal": ROOT_DIR / "gastrohun_llm_en_multimodal_train.jsonl",
}


def read_jsonl(path: Path) -> List[Dict]:
    if not path.exists():
        return []
    rows: List[Dict] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def write_jsonl(path: Path, rows: List[Dict]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def build_sft_subset(rows: List[Dict], ratio: float) -> List[Dict]:
    if not rows:
        return []
    n = max(1, int(len(rows) * ratio))
    random.seed(SEED)
    rows_cp = rows[:]
    random.shuffle(rows_cp)
    subset = rows_cp[:n]
    # Make sure CoT field exists for SFT priority read.
    for r in subset:
        if not r.get("gt_text_cot"):
            answer = str(r.get("answer", r.get("gt_text", "NA"))).strip()
            r["gt_text_cot"] = f"<think>Analyze SSS landmarks and reasoning.</think>\n{answer}"
    return subset


def build_pref_subset(rows: List[Dict]) -> List[Dict]:
    pref_rows = []
    for r in rows:
        has_pref = bool(r.get("chosen")) and (bool(r.get("rejected")) or r.get("doctor_score") is not None)
        if has_pref:
            pref_rows.append(r)
    return pref_rows


def main() -> None:
    for name, src in SOURCES.items():
        rows = read_jsonl(src)
        if not rows:
            print(f"[WARN] missing/empty source: {src}")
            continue

        sft_subset = build_sft_subset(rows, SFT_TRAIN_RATIO)
        pref_subset = build_pref_subset(rows)

        sft_out = ROOT_DIR / f"gastrohun_llm_en_{name}_train_sft_cot_10.jsonl"
        pref_out = ROOT_DIR / f"gastrohun_llm_en_{name}_train_pref.jsonl"

        write_jsonl(sft_out, sft_subset)
        write_jsonl(pref_out, pref_subset)

        print(f"[OK][{name}] sft_cot_10: {len(sft_subset)} -> {sft_out}")
        print(f"[OK][{name}] pref: {len(pref_subset)} -> {pref_out}")


if __name__ == "__main__":
    main()

